2022-04-01 16:03:40,628 INFO    MainThread:369045 [wandb_setup.py:_flush():75] Loading settings from /home/cuongnq1/.config/wandb/settings
2022-04-01 16:03:40,629 INFO    MainThread:369045 [wandb_setup.py:_flush():75] Loading settings from /home/cuongnq1/graph-neural-pde/src/wandb/settings
2022-04-01 16:03:40,629 INFO    MainThread:369045 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-04-01 16:03:40,629 INFO    MainThread:369045 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'src/run_grand_ex.py', 'program': '/home/cuongnq1/graph-neural-pde/src/run_grand_ex.py'}
2022-04-01 16:03:40,629 INFO    MainThread:369045 [wandb_init.py:_log_setup():405] Logging user logs to /home/cuongnq1/graph-neural-pde/src/wandb/run-20220401_160340-2hmughu7/logs/debug.log
2022-04-01 16:03:40,629 INFO    MainThread:369045 [wandb_init.py:_log_setup():406] Logging internal logs to /home/cuongnq1/graph-neural-pde/src/wandb/run-20220401_160340-2hmughu7/logs/debug-internal.log
2022-04-01 16:03:40,629 INFO    MainThread:369045 [wandb_init.py:init():439] calling init triggers
2022-04-01 16:03:40,629 INFO    MainThread:369045 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-04-01 16:03:40,629 INFO    MainThread:369045 [wandb_init.py:init():492] starting backend
2022-04-01 16:03:40,629 INFO    MainThread:369045 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-04-01 16:03:40,643 INFO    MainThread:369045 [backend.py:ensure_launched():219] starting backend process...
2022-04-01 16:03:40,652 INFO    MainThread:369045 [backend.py:ensure_launched():224] started backend process with pid: 369129
2022-04-01 16:03:40,654 INFO    MainThread:369045 [wandb_init.py:init():501] backend started and connected
2022-04-01 16:03:40,662 INFO    MainThread:369045 [wandb_init.py:init():565] updated telemetry
2022-04-01 16:03:40,682 INFO    MainThread:369045 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-04-01 16:04:10,683 INFO    MainThread:369045 [interface_shared.py:_communicate_run():322] couldn't get run from backend
2022-04-01 16:04:10,684 ERROR   MainThread:369045 [wandb_init.py:init():601] backend process timed out
2022-04-01 16:04:10,684 ERROR   MainThread:369045 [wandb_init.py:init():610] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-04-01 16:04:44,208 INFO    MainThread:369045 [wandb_init.py:teardown():253] tearing down wandb.init
